model:
  base_learning_rate: 4.5e-06
  #base_learning_rate: 1.0e-06
  target: ldm.models.autoencoder.VQModel
  params:
    embed_dim: 3
    n_embed: 8192
    monitor: val/rec_loss

    ddconfig:
      attn_type: none
      double_z: false
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual_org_vo_fact0p005.VQLPIPSWithDiscriminatorSino
      #target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 1
        disc_weight: 0.75
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 40
    wrap: true
    train:
      target: ldm.ldm.data.PIL_data_rl.InpaintingTrain_autoencoder
      #target: "sino_data/512x512/data/sino"
      params:
        # For combination of 50 % shapes and 50 % real world data, and 100 % real world data 
        data_root: "/homes/sruban/latent-diffusion-inpainting_sino_trial/sino_data/512x512/Jiaze/data/sino_tv"
        # For 100 % shapes data
        #data_root: "/homes/sruban/latent-diffusion-inpainting_sino_trial/sino_data/512x512/data/sino"
        size: 512
        #crop_size: 256
    validation:
      target: ldm.ldm.data.PIL_data_rl.InpaintingVal_autoencoder
      #target: "sino_data/512x512/data/sino"
      params:
        # For combination of 50 % shapes and 50 % real world data, and 100 % real world data
        data_root: "/homes/sruban/latent-diffusion-inpainting_sino_trial/sino_data/512x512/Jiaze/data/sino_tv"
        # For 100 % shapes data
        #data_root: "/homes/sruban/latent-diffusion-inpainting_sino_trial/sino_data/512x512/data/sino"
        size: 512
        #crop_size: 256
