conditioning:
  main_sampler: resample
  method: ps # Do not touch
  params:
    scale: 0.5

data:
  name: celeb
  root: ./data/samples_sino_512/six_samples
  #root: ./data/samples/512x512/ 

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: random_mask
    mask_prob_range: !!python/tuple [0.1, 0.9]
    image_size: 512


  noise:
    name: gaussian
    sigma: 0
