conditioning:
  main_sampler: resample
  method: ps # Do not touch
  params:
    scale: 0.5

data:
  name: custom
  root: ./data/samples_psmc_512/final_ones_512
  #root: ./data/samples_sino_512/six_samples/smc_tiffs
  #root: ./data/samples/512x512/ 

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: none
    mask_len_range: !!python/tuple [0, 0]
    image_size: 512


  noise:
    name: gaussian
    sigma: 0.1
