conditioning:
  main_sampler: resample
  method: ps # Do not touch
  params:
    scale: 0.5

data:
  name: custom
  root: ./data/samples_sino_512/six_samples/tiffs
  #root: ./data/samples/512x512/ 

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: Missing_Wedge
    mask_len_range: !!python/tuple [10, 20, 30]
    image_size: 512


  noise:
    name: gaussian
    sigma: 0
